package:
  name: buteo
  version: "0.6.7"

source:
  # path: setup.py
  git_rev: "0.6.7"
  git_url: https://github.com/casperfibaek/buteo.git

build:
  number: 0
  script: "$PYTHON -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - gdal
    - numba

test:
  imports:
    - buteo

about:
  home: https://github.com/casperfibaek/buteo/
  license: MIT
  license_familY: MIT
  license_file: LICENSE
  summary: "GIS-thonic way of working with raster and vector data."